version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_test
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db_test
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: